#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

CUR_TIME=`date +%FT%TZ`
DVD_LAYOUT=/data/suse-iso-layout
DVD_TITLE='SUSE-13.2-Joyent'
ISO=openSUSE-13.2-DVD-x86_64.iso
SHA256SUM=openSUSE-13.2-DVD-x86_64.iso.sha256
ISO_DIR=/data/fetched-suse-iso
ISO_FILENAME=./suse-13-joyent.iso
AUTOYAST=./autoinst.xml
GUESTTOOLS=sdc-vmtools
MIRROR=http://opensuse-mirror-gce-us.opensu.se/distribution/13.2/iso
MOUNT_POINT=/mnt/suse13

function fetch_iso() {
    if [ ! -d $ISO_DIR ]; then
        mkdir -p $ISO_DIR
    fi
    
    if [ ! -e $ISO_DIR/$ISO ]; then
        echo "No local copy of $ISO. Fetching latest $ISO"
        curl -s -o $ISO_DIR/$ISO $MIRROR/$ISO
    fi
    
    echo "==> Fetching $SHA256SUM"
    curl -o $ISO_DIR/$SHA256SUM $MIRROR/$SHA256SUM
    
    echo "==> Verifying $ISO with $SHA256SUM"
    
    set +e
    pushd $PWD
    cd $ISO_DIR
    $(shasum -a 512256 -c $SHA256SUM)
    if [[ $? -eq 0 ]]; then
        echo "==> Checksums match, using local copy of $ISO"
    else
        echo "==> Checksums don't match!"
        exit 1
    fi
    popd
    set -e
}

function create_layout() {
    echo "Creating ISO Layout"
    if [ -d $DVD_LAYOUT ]; then
        echo "Layout $DVD_LAYOUT exists...deleting"
        rm -rf $DVD_LAYOUT
    fi
    echo "Creating $DVD_LAYOUT"
    mkdir -p $DVD_LAYOUT

    # Check if $MOUNT_POINT is already mounted
    # This may happen if a previous build failed
    if [ $(grep $MOUNT_POINT /proc/mounts) ]; then
      echo "Unmounting $MOUNT_POINT from previous build..."
        umount $MOUNT_POINT
    fi

    echo "Mounting $ISO to $MOUNT_POINT"
    if [ ! -d $MOUNT_POINT ]; then
        echo "Creating $MOUNT_POINT..."
        mkdir $MOUNT_POINT
    fi
    mount $ISO_DIR/$ISO $MOUNT_POINT -o loop
    pushd $MOUNT_POINT > /dev/null 2>&1
    echo "Populating Layout"
    tar cf - . | tar xpf - -C $DVD_LAYOUT
    popd > /dev/null 2>&1
    umount $MOUNT_POINT
    
    echo "Finished Populating Layout"
}

function copy_autoyast() {
    echo "Copying autoyast file"
    cp $AUTOYAST $DVD_LAYOUT/
}

function copy_guest_tools() {
    echo "Copying $GUESTTOOLS"
    echo "Initiallizing and fetching submodule $GUESTTOOLS"
    git submodule init
    git submodule update
    cp -R ./$GUESTTOOLS/ $DVD_LAYOUT/ 
}


function modify_boot_menu() {
    echo "Modifying grub boot menu"
    cp ./isolinux.cfg $DVD_LAYOUT/isolinux/
}

function cleanup_layout() {
    echo "Cleaning up $DVD_LAYOUT"
    find $DVD_LAYOUT -name TRANS.TBL -exec rm '{}' +
}

function create_newiso() {
    copy_guest_tools
    cleanup_layout
    copy_autoyast
    modify_boot_menu
    echo "Preparing NEW ISO"
    pushd $DVD_LAYOUT > /dev/null 2>&1
    discinfo=`head -1 .discinfo`
    echo "Creating NEW ISO"
    mkisofs -r -R -J -T -v \
     -no-emul-boot -boot-load-size 4 -boot-info-table \
     -V "$DVD_TITLE" -p "Joyent" \
     -A "$DVD_TITLE - $CUR_TIME" \
     -b isolinux/isolinux.bin -c isolinux/boot.cat \
     -x "lost+found" -o $ISO_FILENAME $DVD_LAYOUT
    echo "Fixing up NEW ISO"
    echo implantisomd5 $ISO_FILENAME
    implantisomd5 $ISO_FILENAME
    popd > /dev/null 2>&1
    echo "NEW ISO $ISO_FILENAME is ready"
}

# main line

usage()
{
    cat <<EOF
Usage:
        $0 [options] command [command]
option:
        -h                    - this usage

Commands:
        fetch                 - fetch ISO
        layout                - create layout for new ISO
        finish                - create the new ISO

EOF
    exit 1
}

args=`getopt -o h -n 'build_centos_iso.sh' -- "$@"`

if [[ $# == 0 ]]; then
    usage;
fi

eval set -- $args

while true ; do
   case "$1" in
       -h)
            usage;
            break;;
       --)
           shift; break;;
   esac
done

for arg ; do
    if [ $arg = 'fetch' ] ; then
        fetch_iso
    fi
    if [ $arg = 'layout' ] ; then
        create_layout
    fi
    if [ $arg = 'finish' ] ; then
        create_newiso
    fi
done
